export const regexes = [
	/\[Server thread\/INFO\]: ((\w*) (was shot by \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was shot by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was pummeled by \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was pummeled by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (walked into a cactus whilst trying to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was pricked to death))/i,
	/\[Server thread\/INFO\]: ((\w*) (drowned whilst trying to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (drowned))/i,
	/\[Server thread\/INFO\]: ((\w*) (experienced kinetic energy whilst trying to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (experienced kinetic energy))/i,
	/\[Server thread\/INFO\]: ((\w*) (was blown up by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was blown up by \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (blew up))/i,
	/\[Server thread\/INFO\]: ((\w*) (was killed by \[Intentional Game Design\]))/i,
	/\[Server thread\/INFO\]: ((\w*) (hit the ground too hard whilst trying to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (hit the ground too hard))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell from a high place))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell off a ladder))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell off some vines))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell off some weeping vines))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell off some twisting vines))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell off scaffolding))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell while climbing))/i,
	/\[Server thread\/INFO\]: ((\w*) (was impaled on a stalagmite whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was impaled on a stalagmite))/i,
	/\[Server thread\/INFO\]: ((\w*) (was squashed by a falling anvil whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was squashed by a falling anvil))/i,
	/\[Server thread\/INFO\]: ((\w*) (was squashed by a falling block whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was squashed by a falling block))/i,
	/\[Server thread\/INFO\]: ((\w*) (was skewered by a falling stalactite whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was skewered by a falling stalactite))/i,
	/\[Server thread\/INFO\]: ((\w*) (walked into fire whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (went up in flames))/i,
	/\[Server thread\/INFO\]: ((\w*) (was burnt to a crisp whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (burned to death))/i,
	/\[Server thread\/INFO\]: ((\w*) (went off with a bang due to a firework fired from \w* by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (went off with a bang))/i,
	/\[Server thread\/INFO\]: ((\w*) (tried to swim in lava to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (tried to swim in lava))/i,
	/\[Server thread\/INFO\]: ((\w*) (was struck by lightning whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was struck by lightning))/i,
	/\[Server thread\/INFO\]: ((\w*) (walked into danger zone due to \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (discovered the floor was lava))/i,
	/\[Server thread\/INFO\]: ((\w*) (was killed by magic whilst trying to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was killed by magic))/i,
	/\[Server thread\/INFO\]: ((\w*) (was killed by \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was killed by \w* using magic))/i,
	/\[Server thread\/INFO\]: ((\w*) (froze to death))/i,
	/\[Server thread\/INFO\]: ((\w*) (was frozen to death by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was slain by \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was slain by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was fireballed by \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was fireballed by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was stung to death by \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was stung to death))/i,
	/\[Server thread\/INFO\]: ((\w*) (was shot by a skull from \w* using \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was shot by a skull from \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was obliterated by a sonically-charged shriek whilst trying to escape \w* wielding \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was obliterated by a sonically-charged shriek))/i,
	/\[Server thread\/INFO\]: ((\w*) (starved to death whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (starved to death))/i,
	/\[Server thread\/INFO\]: ((\w*) (suffocated in a wall whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (suffocated in a wall))/i,
	/\[Server thread\/INFO\]: ((\w*) (was squished too much))/i,
	/\[Server thread\/INFO\]: ((\w*) (was squashed by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was poked to death by a sweet berry bush whilst trying to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was poked to death by a sweet berry bush))/i,
	/\[Server thread\/INFO\]: ((\w*) (was killed by \w* trying to hurt \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was killed trying to hurt \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was impaled by \w* with \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (was impaled by \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (didn't want to live in the same world as \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (fell out of the world))/i,
	/\[Server thread\/INFO\]: ((\w*) (withered away whilst fighting \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (withered away))/i,
	/\[Server thread\/INFO\]: ((\w*) (died from dehydration whilst trying to escape \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (died from dehydration))/i,
	/\[Server thread\/INFO\]: ((\w*) (died because of \w*))/i,
	/\[Server thread\/INFO\]: ((\w*) (died))/i
];
