export const regexes = [
	/\[Server thread\/INFO\]: (.* was shot by .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* was shot by .*)/gi,
	/\[Server thread\/INFO\]: (.* was pummeled by .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* was pummeled by .*)/gi,
	/\[Server thread\/INFO\]: (.* walked into a cactus whilst trying to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* was pricked to death)/gi,
	/\[Server thread\/INFO\]: (.* drowned whilst trying to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* drowned)/gi,
	/\[Server thread\/INFO\]: (.* experienced kinetic energy whilst trying to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* experienced kinetic energy)/gi,
	/\[Server thread\/INFO\]: (.* was blown up by .*)/gi,
	/\[Server thread\/INFO\]: (.* was blown up by .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* blew up)/gi,
	/\[Server thread\/INFO\]: (.* was killed by \[Intentional Game Design\])/gi,
	/\[Server thread\/INFO\]: (.* hit the ground too hard whilst trying to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* hit the ground too hard)/gi,
	/\[Server thread\/INFO\]: (.* fell from a high place)/gi,
	/\[Server thread\/INFO\]: (.* fell off a ladder)/gi,
	/\[Server thread\/INFO\]: (.* fell off some vines)/gi,
	/\[Server thread\/INFO\]: (.* fell off some weeping vines)/gi,
	/\[Server thread\/INFO\]: (.* fell off some twisting vines)/gi,
	/\[Server thread\/INFO\]: (.* fell off scaffolding)/gi,
	/\[Server thread\/INFO\]: (.* fell while climbing)/gi,
	/\[Server thread\/INFO\]: (.* was impaled on a stalagmite whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* was impaled on a stalagmite)/gi,
	/\[Server thread\/INFO\]: (.* was squashed by a falling anvil whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* was squashed by a falling anvil)/gi,
	/\[Server thread\/INFO\]: (.* was squashed by a falling block whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* was squashed by a falling block)/gi,
	/\[Server thread\/INFO\]: (.* was skewered by a falling stalactite whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* was skewered by a falling stalactite)/gi,
	/\[Server thread\/INFO\]: (.* walked into fire whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* went up in flames)/gi,
	/\[Server thread\/INFO\]: (.* was burnt to a crisp whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* burned to death)/gi,
	/\[Server thread\/INFO\]: (.* went off with a bang due to a firework fired from .* by .*)/gi,
	/\[Server thread\/INFO\]: (.* went off with a bang)/gi,
	/\[Server thread\/INFO\]: (.* tried to swim in lava to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* tried to swim in lava)/gi,
	/\[Server thread\/INFO\]: (.* was struck by lightning whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* was struck by lightning)/gi,
	/\[Server thread\/INFO\]: (.* walked into danger zone due to .*)/gi,
	/\[Server thread\/INFO\]: (.* discovered the floor was lava)/gi,
	/\[Server thread\/INFO\]: (.* was killed by magic whilst trying to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* was killed by magic)/gi,
	/\[Server thread\/INFO\]: (.* was killed by .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* was killed by .* using magic)/gi,
	/\[Server thread\/INFO\]: (.* froze to death)/gi,
	/\[Server thread\/INFO\]: (.* was frozen to death by .*)/gi,
	/\[Server thread\/INFO\]: (.* was slain by .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* was slain by .*)/gi,
	/\[Server thread\/INFO\]: (.* was fireballed by .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* was fireballed by .*)/gi,
	/\[Server thread\/INFO\]: (.* was stung to death by .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* was stung to death)/gi,
	/\[Server thread\/INFO\]: (.* was shot by a skull from .* using .*)/gi,
	/\[Server thread\/INFO\]: (.* was shot by a skull from .*)/gi,
	/\[Server thread\/INFO\]: (.* was obliterated by a sonically-charged shriek whilst trying to escape .* wielding .*)/gi,
	/\[Server thread\/INFO\]: (.* was obliterated by a sonically-charged shriek)/gi,
	/\[Server thread\/INFO\]: (.* starved to death whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* starved to death)/gi,
	/\[Server thread\/INFO\]: (.* suffocated in a wall whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* suffocated in a wall)/gi,
	/\[Server thread\/INFO\]: (.* was squished too much)/gi,
	/\[Server thread\/INFO\]: (.* was squashed by .*)/gi,
	/\[Server thread\/INFO\]: (.* was poked to death by a sweet berry bush whilst trying to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* was poked to death by a sweet berry bush)/gi,
	/\[Server thread\/INFO\]: (.* was killed by .* trying to hurt .*)/gi,
	/\[Server thread\/INFO\]: (.* was killed trying to hurt .*)/gi,
	/\[Server thread\/INFO\]: (.* was impaled by .* with .*)/gi,
	/\[Server thread\/INFO\]: (.* was impaled by .*)/gi,
	/\[Server thread\/INFO\]: (.* didn't want to live in the same world as .*)/gi,
	/\[Server thread\/INFO\]: (.* fell out of the world)/gi,
	/\[Server thread\/INFO\]: (.* withered away whilst fighting .*)/gi,
	/\[Server thread\/INFO\]: (.* withered away)/gi,
	/\[Server thread\/INFO\]: (.* died from dehydration whilst trying to escape .*)/gi,
	/\[Server thread\/INFO\]: (.* died from dehydration)/gi,
	/\[Server thread\/INFO\]: (.* died because of .*)/gi,
	/\[Server thread\/INFO\]: (.* died)/gi
];
